package com.enonic.cms.portal.xtrace;

import com.enonic.cms.portal.livetrace.PortalRequestTrace;

public class JsonSerializer
{
    public String serialize( PortalRequestTrace requestTrace )
    {
        return "{  \"xtrace\": {    \"version\": 1,    \"page\": {      \"key\": 73,      \"name\": \"Home\",      \"cacheable\": false,      \"cache_hit\": false,      \"page_template_name\": \"document\",      \"start_time\": 0,      \"end_time\": 1692,      \"xslt\": {        \"processing_time\": 28      },      \"total_time\": 1692,      \"run_as_user\": \"local\\\\tan\",      \"functions\": [        {          \"name\": \"getMenuBranch\",          \"start_time\": 0,          \"end_time\": 1,          \"time\": 128        }      ],      \"windows\": [        {          \"key\": 1925,          \"name\": \"Frontpage banner (950px)\",          \"cacheable\": true,          \"cache_hit\": true,          \"start_time\": 128,          \"end_time\": 480,          \"total_time\": 352,          \"xslt\": {            \"processing_time\": 7          },          \"functions\": [            {              \"name\": \"getContentBySection\",              \"start_time\": 128,              \"end_time\": 1,              \"time\": 345            }          ]        },        {          \"key\": 1926,          \"name\": \"Case studies (frontpage box)\",          \"cacheable\": true,          \"cache_hit\": true,          \"start_time\": 480,          \"end_time\": 1368,          \"total_time\": 888,          \"xslt\": {            \"processing_time\": 19          },          \"functions\": [            {              \"name\": \"getContentBySection\",              \"start_time\": 480,              \"end_time\": 1,              \"time\": 39            },            {              \"name\": \"getContentBySection\",              \"start_time\": 519,              \"end_time\": 1,              \"time\": 528            },            {              \"name\": \"getMenuItem\",              \"start_time\": 1047,              \"end_time\": 1,              \"time\": 3            },            {              \"name\": \"getContentBySection\",              \"start_time\": 1050,              \"end_time\": 1,              \"time\": 295            },            {              \"name\": \"getMenuItem\",              \"start_time\": 1345,              \"end_time\": 1,              \"time\": 4            }          ]        },        {          \"key\": 1926,          \"name\": \"Vignette list (boxes)\",          \"cacheable\": true,          \"cache_hit\": true,          \"start_time\": 1368,          \"end_time\": 1664,          \"total_time\": 296,          \"xslt\": {            \"processing_time\": 19          },          \"functions\": [            {              \"name\": \"getContentBySection\",              \"start_time\": 1368,              \"end_time\": 1,              \"time\": 287            }          ]        }      ]    }  }}";
    }
}
